openapi: 3.0.3
info:
  title: OfferZone API
  version: 1.0.0
  description: >
    OfferZone is a multi-role offer listing platform.
    - Customers can view offers by city, area, category, brand, or product.
    - Retailers can add, update, and delete products and offers.
servers:
  - url: http://localhost:8000/offerzone
    description: Local development server

tags:
  - name: Authentication
    description: Retailer and Customer authentication
  - name: Products
    description: Product management for retailers
  - name: Offers
    description: Offer management and filtering

paths:
  /auth:
    post:
      tags: [Authentication]
      summary: Signup (Customer or Retailer)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password, role]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [customer, retailer]
      responses:
        '201':
          description: User successfully created
        '400':
          description: Invalid or missing fields

  /auth/session:
    post:
      tags: [Authentication]
      summary: Login (Customer or Retailer)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful (returns JWT token)
        '401':
          description: Invalid credentials

  /auth/me:
    get:
      tags: [Authentication]
      summary: Get current user details
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Returns authenticated user profile
        '401':
          description: Missing or invalid token

  /products:
    post:
      tags: [Products]
      summary: Add a new product
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully

    get:
      tags: [Products]
      summary: Get all products
      responses:
        '200':
          description: Returns all products

  /products/filter:
    get:
      tags: [Products]
      summary: Filter products by city, category, brand
      parameters:
        - name: city
          in: query
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
        - name: brand
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Returns matching products
        '404':
          description: No products found

  /products/{id}:
    get:
      tags: [Products]
      summary: Get a single product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product found
        '404':
          description: Product not found
    put:
      tags: [Products]
      summary: Update a product
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated
    delete:
      tags: [Products]
      summary: Delete a product
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted

  /offers:
    post:
      tags: [Offers]
      summary: Create a new offer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Offer'
      responses:
        '201':
          description: Offer created successfully

    get:
      tags: [Offers]
      summary: Get all offers
      responses:
        '200':
          description: Returns all offers

  /offers/mine:
    get:
      tags: [Offers]
      summary: Get all offers created by the logged-in retailer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of retailer’s offers

  /offers/filter:
    get:
      tags: [Offers]
      summary: Filter offers by city, area, category, brand, or product
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: string
        - name: area
          in: query
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
        - name: brand
          in: query
          schema:
            type: string
        - name: product
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Filtered list of offers
        '404':
          description: No offers found

  /offers/{id}:
    get:
      tags: [Offers]
      summary: Get an offer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Offer details
        '404':
          description: Offer not found
    put:
      tags: [Offers]
      summary: Update an offer
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Offer'
      responses:
        '200':
          description: Offer updated successfully
    delete:
      tags: [Offers]
      summary: Delete an offer
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Offer deleted

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      required:
        - name
        - brand
        - category
        - price
        - city
        - area
      properties:
        name:
          type: string
        brand:
          type: string
        category:
          type: string
        description:
          type: string
        price:
          type: number
        city:
          type: string
        area:
          type: string
        image:
          type: string

    Offer:
      type: object
      required:
        - product
        - title
        - discountPercent
        - originalPrice
        - offerPrice
        - city
        - area
        - validFrom
        - validTill
      properties:
        product:
          type: string
          description: ObjectId of the product
        title:
          type: string
        description:
          type: string
        discountPercent:
          type: number
        originalPrice:
          type: number
        offerPrice:
          type: number
        validFrom:
          type: string
          format: date
        validTill:
          type: string
          format: date
        city:
          type: string
        area:
          type: string
        isPremium:
          type: boolean
